apiVersion: v1 
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: database
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: database
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels: 
      project: roboshop
      component: rabbitmq
      tier: database
    # This is pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: database
    spec:
      containers:
      - name: shipping
        image: rabbitmq:3
        envFrom:
          - secretRef:
              name: rabbitmq
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: database
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672