apiVersion: v1 
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
data:
  REDIS_URL: 'redis://redis:6379' 
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: maheswari450/user-optimise:v1
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1 
kind: Service
metadata:
  name: user
  namespace: roboshop
  selector:
    component: user
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080